## SVM(Suppoert Vector Machine)
---
- ML에서 오랫동안 연구되었고 성능이 좋은 모델
- DL보다 성능이 좋은 경우도 있음

In [1]:
# 모듈 로딩
from sklearn.svm import SVC
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

### [1] 데이터 준비

In [2]:
digits = load_digits()
# data2 = load_digits()
print(digits.data.shape)

(1797, 64)


In [3]:
# data, target 분리
data=digits['data']
target=digits['target']

In [4]:
print(f'data : {data.shape}, target : {target.shape}')

data : (1797, 64), target : (1797,)


In [5]:
print(f'data[0] : \n {data[0]}')

data[0] : 
 [ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]


In [6]:
print(f'Target : {target[2]} - images[2] \n\n {digits["images"][2]}')

Target : 2 - images[2] 

 [[ 0.  0.  0.  4. 15. 12.  0.  0.]
 [ 0.  0.  3. 16. 15. 14.  0.  0.]
 [ 0.  0.  8. 13.  8. 16.  0.  0.]
 [ 0.  0.  1.  6. 15. 11.  0.  0.]
 [ 0.  1.  8. 13. 15.  1.  0.  0.]
 [ 0.  9. 16. 16.  5.  0.  0.  0.]
 [ 0.  3. 13. 16. 16. 11.  5.  0.]
 [ 0.  0.  0.  3. 11. 16.  9.  0.]]


In [7]:
# 학습용, 테스트용 데이터 분리 => 8:2     # test_size = 0.2
train_input, test_input, train_target, test_target = train_test_split(
data, target, random_state=42, test_size=0.2)

In [8]:
# 모델 생성
model1=LogisticRegression(max_iter=500)

# 학습
model1.fit(train_input, train_target)

# 평가
print(f"훈련 세트 정확도: , {model1.score(train_input, train_target)}")
print(f"테스트 세트 정확도: , {model1.score(test_input, test_target)}")

훈련 세트 정확도: , 1.0
테스트 세트 정확도: , 0.975


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
prescore = model1.predict([data[9]])
print(f" 로지스틱 예측: {prescore}")

 로지스틱 예측: [9]


In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC


In [11]:
from sklearn.preprocessing import MinMaxScaler

# 훈련데이터에 대해 스케일링 적용을 위한 조사
scaler = MinMaxScaler()
scaler.fit(train_input)

# 훈련데이터에 대해 스케일링 적용
train_input_scaled = scaler.transform(train_input)

# 테스트데이터에 대해 스케일링 적용
test_input_scaled = scaler.transform(test_input)

In [12]:
# gamma 파라미터 조정
model2 = SVC(gamma=0.01).fit(train_input_scaled, train_target)

# 평가
print(f"훈련 세트 정확도: , {model2.score(train_input_scaled, train_target)}")
print(f"테스트 세트 정확도: , {model2.score(test_input_scaled, test_target)}")

훈련 세트 정확도: , 0.965205288796103
테스트 세트 정확도: , 0.95


In [13]:
prescore1 = model2.predict(scaler.transform([data[9]]))
prescore1
print(f" 스케일 SVC 예측: {prescore1}")

 스케일 SVC 예측: [9]


In [14]:
print(f"로지스틱 훈련 세트 정확도: , {model1.score(train_input, train_target)}")
print(f"로지스틱 테스트 세트 정확도: , {model1.score(test_input, test_target)}")
print(f"스케일 SVC 훈련 세트 정확도: , {model2.score(train_input_scaled, train_target)}")
print(f"스케일 SVC 테스트 세트 정확도: , {model2.score(test_input_scaled, test_target)}")

로지스틱 훈련 세트 정확도: , 1.0
로지스틱 테스트 세트 정확도: , 0.975
스케일 SVC 훈련 세트 정확도: , 0.965205288796103
스케일 SVC 테스트 세트 정확도: , 0.95


In [15]:
print(f"로지스틱 예측: {prescore}")
print(f"스케일 SVC 예측: {prescore1}")

로지스틱 예측: [9]
스케일 SVC 예측: [9]


In [16]:
for i in range(1, 10):
    prescore = model1.predict([data[i]])
    print(f"로지스틱 {i} 예측: {prescore}")
    
for i in range(1, 10):
    prescore1 = model2.predict(scaler.transform([data[i]]))
    print(f"스케일 SVC {i} 예측: {prescore1}")

로지스틱 1 예측: [1]
로지스틱 2 예측: [2]
로지스틱 3 예측: [3]
로지스틱 4 예측: [4]
로지스틱 5 예측: [5]
로지스틱 6 예측: [6]
로지스틱 7 예측: [7]
로지스틱 8 예측: [8]
로지스틱 9 예측: [9]
스케일 SVC 1 예측: [1]
스케일 SVC 2 예측: [1]
스케일 SVC 3 예측: [3]
스케일 SVC 4 예측: [4]
스케일 SVC 5 예측: [9]
스케일 SVC 6 예측: [6]
스케일 SVC 7 예측: [7]
스케일 SVC 8 예측: [8]
스케일 SVC 9 예측: [9]


In [17]:
#######################################################################

In [18]:
# pipeline
# clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
# clf.fit(data, target)
# Pipeline(steps=[('standardscaler', StandardScaler()),
#                 ('svc', SVC(gamma='auto'))])

In [19]:
# plt.gray()
# plt.matshow(digits.images[0])
# plt.show()