## LogisticRegression
---
- 인공신경망의 기본 개념과 동일
- Regression이지만 다중분류로 사용

- 선형모델 기반으로 y=wx+b 그대로 사용

- y=wx+b의 결과=> 분류 변환 함수 => sigmoid()

In [64]:
# 모듈
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

In [65]:
data, target = load_iris(as_frame=True, return_X_y=True)
type(data), type(target)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [66]:
data.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [67]:
target

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [68]:
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [74]:
data=data.loc[:, data.columns[1:]]

print('data =>', data.shape)

data => (150, 3)


In [75]:
data1 = data.drop(range(50,100), axis=0)
data1

sepal width (cm)  petal length (cm)  petal width (cm)
0                 3.5                1.4               0.2
1                 3.0                1.4               0.2
2                 3.2                1.3               0.2
3                 3.1                1.5               0.2
4                 3.6                1.4               0.2
..                ...                ...               ...
145               3.0                5.2               2.3
146               2.5                5.0               1.9
147               3.0                5.2               2.0
148               3.4                5.4               2.3
149               3.0                5.1               1.8

[100 rows x 3 columns]

In [76]:
target1 = target.drop(range(50,100), axis=0)
target1

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 100, dtype: int32

In [77]:
from sklearn.model_selection import train_test_split

train_x, test_x, train_y, test_y = train_test_split(
    data1, target1, test_size=0.2, random_state=42, stratify=target1)

print(train_x.shape, test_x.shape)
print(train_y.value_counts(), test_y.value_counts())

(80, 3) (20, 3)
0    40
2    40
Name: target, dtype: int64 2    10
0    10
Name: target, dtype: int64


In [78]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_x, train_y)

print(lr.score(train_x, train_y))
print(lr.score(test_x, test_y))

1.0
1.0


In [79]:
pre=lr.predict(train_x)
pre

array([0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2,
       0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2,
       0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0])

In [32]:
pre1=lr.predict(test_x)
pre1

array([2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2])

In [34]:
lr.predict([[0.5, 4.5, 3.0]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2])

In [35]:
probay=lr.predict_proba([[0.5, 4.5, 3.0]])
print('분류항목: ', lr.classes_)
print('예측확률: ', probay)

분류항목:  [0 2]
예측확률:  [[0.01496041 0.98503959]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [43]:
# 결정함수
ret = lr.decision_function([[0.5, 4.5, 3.0]])
print(np.round(ret, 3))

[4.187]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [38]:
# y=ax+b : 모델 파라미터
result = (lr.coef_ * 0.5, 4.5, 3.0) + lr.intercept_
print('result: ', result)

result:  [array([[-6.65405626, -5.61073578, -6.10935392]]) -2.0329384196560882
 -3.5329384196560882]


C:\Users\User\AppData\Local\Temp\ipykernel_2604\3897344363.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = (lr.coef_ * 0.5, 4.5, 3.0) + lr.intercept_


In [44]:
# 시그모이드 함수 expit(ax+b)/ 소프트맥스 함수 softmax(ax+b) 후 결과 확인
from scipy.special import softmax, expit
sigValue2=expit(ret)
print('예측확률: ', np.round(sigValue2, 5))
print('예측확률: ', np.round(probaY, 5))

예측확률:  [0.98504]


NameError: name 'probaY' is not defined