# Numpy 패키지 --------------------------------------

- pandas에서 데이터를 저장 및 처리에 사용되는 패키지

- 외부 패키지로 반드시 설치 필요

- 고속 데이터 처리, 수치 계산 수행 패키지

- 머신러닝/딥러닝용 패키지 Scikit-lern, Tensorflow, PyTorch, Keras 등등에서도 
- 내부 데이터 저장 및 수치 계산 사용되는 패키지

- [중요] 동일한 데이터 타입의 데이터를 저장하는 배열(Array) 타입!

- 설치 : !pip install numpy (jupyter notebook에서 사용)

In [1]:
# 모듈 로딩 및 버전 확인 -----------------------------------
import numpy as np

np.__version__

'1.21.5'

In [2]:
# ndarray 객체 생성 하기 ----------------------------------> numpy.array()

arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
type(arr1)

numpy.ndarray

In [7]:
# ndarray 객체 속성 확인하기 -------------------------------
# 객체변수명, 속성명
# ndim : 차원 ( 예:1, 2, 3.....)
# shape : 형태 ( 예: (갯수, ), (행, 열), (면, 행, 열))
# dtype : 데이터 타입
# itemsize : 배열 요소의 바이트 크기
# size : 배열 요소 갯수
print( arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size, sep='\n')

1
(3,)
int32
4
3


In [11]:
# 배열의 요소 즉 아이템, 원소 접근하기 ----------------------
# 0-base 인덱스 자동 지정 => 객체변수명[ 인덱스 ]
print(f'객체변수명 arr1 => {arr1}')
print(f'객체변수명 arr1[0] => {arr1[0]}')
print(f'객체변수명 arr1[1] => {arr1[1]}')

객체변수명 arr1 => [1 2 3]
객체변수명 arr1[0] => 1
객체변수명 arr1[1] => 2


In [17]:
# 모든 값을 1로 채워서 ndarray 객체 생성 함수 => ones()
arr2=np.array([1,1,1,1])
arr2=np.ones(4, dtype=np.int16)
arr2

array([1, 1, 1, 1], dtype=int16)

In [19]:
print( arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size, sep='\n')
print(f'객체변수명 arr2 => {arr2}')
print(f'객체변수명 arr2[0] => {arr2[0]}')
print(f'객체변수명 arr2[1] => {arr2[1]}')

1
(4,)
int16
2
4
객체변수명 arr2 => [1 1 1 1]
객체변수명 arr2[0] => 1
객체변수명 arr2[1] => 1


In [20]:
# 초기화하지 않고 ndarray 객체 생성 => numpy.empty()
arr3=np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr3=np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# 2차원 형태의 ndarray 객체 생성
arr4=np.array([[1,2,3],[4,5,6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr4.shape, arr4.ndim

((2, 3), 2)

In [26]:
# 2차원 => 1차원
arr5=arr4.flatten()

In [27]:
arr5.shape, arr4.ndim

((6,), 2)

In [28]:
# 1차원 => 다른 차원으로 변경   reshape()
arr6=arr5.reshape((1,6))
arr6

array([[1, 2, 3, 4, 5, 6]])

In [29]:
arr6=arr5.reshape((2,3))
arr6

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr6=arr5.reshape((1,3,2))
arr6

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [32]:
arr7=arr6.flatten()
arr7.shape, arr7.ndim

((6,), 1)

In [34]:
# 차원/형태 변환 => reshape(-1, n), reshape(n, -1)
arr8=np.arange(8)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
arr9=arr8.reshape(-1,2)
arr9

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [36]:
# arr9=arr8.reshape(-1,3)             크기가 맞아야한다!
# arr9

In [37]:
arr9=arr8.reshape(2, -1)
arr9

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
arr9=arr8.reshape(-1, 1)
arr9

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])