## IRIS Dataset 활용 분류

In [2]:
# 모듈
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

### [1] 데이터 로딩 및 확인

In [3]:
#iris=load_iris(as_frame=True, return_X_y=True)
# type(iris), type(iris[0]), type(iris[1])
data, target = load_iris(as_frame=True, return_X_y=True)
type(data), type(target)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [4]:
print(data.info(), data.head(3), sep='\n\n')
# print(iris[0].info(), iris[0].head(3), sep='\n\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2


In [5]:
print(target.head(3), target.unique(), target.value_counts(), sep='\n\n')

0    0
1    0
2    0
Name: target, dtype: int32

[0 1 2]

0    50
1    50
2    50
Name: target, dtype: int64


#### [2] 학습 데이터 준비

In [6]:
data.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [7]:
# 데이터 => petal_length (cm), petal_width (cm)
# 타  겟 => 0 , 2
data = data.loc[:, data.columns[2:]]

print('data =>', data.shape)

data => (150, 2)


In [13]:
data1 = data.drop(range(50,100), axis=0)
data1

petal length (cm)  petal width (cm)
0                  1.4               0.2
1                  1.4               0.2
2                  1.3               0.2
3                  1.5               0.2
4                  1.4               0.2
..                 ...               ...
145                5.2               2.3
146                5.0               1.9
147                5.2               2.0
148                5.4               2.3
149                5.1               1.8

[100 rows x 2 columns]

In [15]:
target1 = target.drop(range(50,100), axis=0)
target1

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 100, dtype: int32

In [16]:
# 학습용, 테스트용 데이터 분리
from sklearn.model_selection import train_test_split

In [28]:
# train:test = 75%:25%
# test_size= o.x
# stratify => 분류 항목 비율 맞추어서 데이터셋 설정
# random_state => 매번 동일하게 데이터 구성하는 경우 지정
train_x, test_x, train_y, test_y = train_test_split(
    data1, target1, test_size=0.2, random_state=42, stratify=target1) # stratify=target

In [29]:
print(train_x.shape, test_x.shape)
print(train_y.value_counts(), test_y.value_counts())

(80, 2) (20, 2)
0    40
2    40
Name: target, dtype: int64 2    10
0    10
Name: target, dtype: int64


In [35]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_x, train_y)

print(lr.score(train_x, train_y))
print(lr.score(test_x, test_y))

1.0
1.0


In [37]:
pre=lr.predict(train_x)
pre

array([0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2, 2, 2,
       0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2,
       0, 2, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0])

In [43]:
pre1=lr.predict(test_x)
pre1

array([2, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2])

In [44]:
lr.predict([[0.5, 4.5]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [41]:
pre=lr.predict([[0.5, 4.5]])
pre

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])