# 미국 고등학생의 시험에서의 성과
---
    * 학부모의 배경, 시험 준비 등이 학생들의 성적에 미치는 영향

In [1]:
# 모듈
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')
from sklearn.model_selection import train_test_split
from sklearn.utils import all_estimators
from sklearn.preprocessing import LabelEncoder

In [2]:
# 파일
DIR='../DAY-0907/StudentsPerformance.csv'
FILE=pd.read_csv(DIR)
stuDF=(FILE)

In [3]:
# 확인
stuDF.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [4]:
# 결측치 확인
stuDF.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [5]:
# 열 확인
stuDF.columns

# gender: 성별
# race/ethnicity: 인종/민족
# parental level of education: 부모의 교육 수준
# lunch: 점심
# test preparation course: 시험 준비 과정
# math score: 수학 점수
# reading score: 읽기 점수
# writing score: 쓰기 점수

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [6]:
# applpus score(과목 3개의 합산 점수) 와 allscore level(등급의 평균) 추가
stuDF['allplus score']=stuDF['math score']+stuDF['reading score']+stuDF['writing score']
stuDF['allscore level']=stuDF['allplus score']/3

In [7]:
# 3개의 성적을 합산한 것의 평균을 구하고 점수별 등급을 지정
level = []
for i in stuDF['allscore level']:
    if (i <=100 )&( i >=70):
        level.append(1)
    elif (i <70) & (i >=40):
        level.append(2)
    else:
        level.append(3)
print(level)        

[1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 3, 1, 2, 2, 3, 1, 3, 2, 1, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 2, 2, 2, 3, 1, 1, 1, 2, 1, 1, 3, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 3, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 3, 2, 2, 1, 1, 1, 3, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2, 3, 1, 2, 2, 3, 2, 

In [8]:
# 등급 만들어준 것을 새로운 열로 추가
stuDF['Rank']=level

In [9]:
# 라벨 인코딩을 통해 문자열이었던 다른 열들도 숫자로 바꾸어줌 (예를들어 0, 1, 2, 3)
label=stuDF[['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course']]
for i in label:
    encoder = LabelEncoder()
    encoder.fit(stuDF[i])
    stuDF[i] = encoder.transform(stuDF[i])
    print(i)
    print(encoder.classes_)
    print('------------------------------')

gender
['female' 'male']
------------------------------
race/ethnicity
['group A' 'group B' 'group C' 'group D' 'group E']
------------------------------
parental level of education
["associate's degree" "bachelor's degree" 'high school' "master's degree"
 'some college' 'some high school']
------------------------------
lunch
['free/reduced' 'standard']
------------------------------
test preparation course
['completed' 'none']
------------------------------


## 모델
---

In [10]:
stuDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   gender                       1000 non-null   int32  
 1   race/ethnicity               1000 non-null   int32  
 2   parental level of education  1000 non-null   int32  
 3   lunch                        1000 non-null   int32  
 4   test preparation course      1000 non-null   int32  
 5   math score                   1000 non-null   int64  
 6   reading score                1000 non-null   int64  
 7   writing score                1000 non-null   int64  
 8   allplus score                1000 non-null   int64  
 9   allscore level               1000 non-null   float64
 10  Rank                         1000 non-null   int64  
dtypes: float64(1), int32(5), int64(5)
memory usage: 66.5 KB


In [11]:
# data, target 지정
data=stuDF[['gender','race/ethnicity','parental level of education','lunch','test preparation course']]
target=stuDF['Rank']

In [12]:
print(data.shape)
print(target.shape)

(1000, 5)
(1000,)


In [13]:
# 훈련 테스트 분리
train_X, test_X, train_y, test_y = train_test_split(data, target,
                                                    test_size=0.2,
                                                   shuffle=True,
                                                    stratify=target,
                                                   random_state=42)

In [14]:
scores = []
models = all_estimators(type_filter='classifier')
for name, model in models:
    try:
        # 모델 객체 생성
        md=model()
        # 학습
        md.fit(train_X, train_y)
        # 평가
        result=md.score(test_X, test_y)
        scores.append((name, result))
    except:
        pass
scores

[('AdaBoostClassifier', 0.575),
 ('BaggingClassifier', 0.495),
 ('BernoulliNB', 0.59),
 ('CalibratedClassifierCV', 0.61),
 ('CategoricalNB', 0.61),
 ('ComplementNB', 0.605),
 ('DecisionTreeClassifier', 0.505),
 ('DummyClassifier', 0.51),
 ('ExtraTreeClassifier', 0.515),
 ('ExtraTreesClassifier', 0.515),
 ('GaussianNB', 0.61),
 ('GaussianProcessClassifier', 0.6),
 ('GradientBoostingClassifier', 0.59),
 ('HistGradientBoostingClassifier', 0.555),
 ('KNeighborsClassifier', 0.545),
 ('LabelPropagation', 0.55),
 ('LabelSpreading', 0.54),
 ('LinearDiscriminantAnalysis', 0.61),
 ('LinearSVC', 0.61),
 ('LogisticRegression', 0.61),
 ('LogisticRegressionCV', 0.61),
 ('MLPClassifier', 0.6),
 ('MultinomialNB', 0.615),
 ('NearestCentroid', 0.35),
 ('PassiveAggressiveClassifier', 0.475),
 ('Perceptron', 0.52),
 ('QuadraticDiscriminantAnalysis', 0.6),
 ('RadiusNeighborsClassifier', 0.615),
 ('RandomForestClassifier', 0.535),
 ('RidgeClassifier', 0.61),
 ('RidgeClassifierCV', 0.61),
 ('SGDClassifier', 

In [15]:
from sklearn.linear_model import LogisticRegression

# 모델 생성
model=LogisticRegression(max_iter=500)

# 학습
model.fit(train_X.values, train_y.values)

# 평가
print(f"훈련 세트 정확도: , {model.score(train_X.values, train_y.values)}")
print(f"테스트 세트 정확도: , {model.score(test_X.values, test_y.values)}")
print('분류 종류 : ', model.classes_)
print('가중치 값 : ', model.coef_)
print('절 편 값 : ', model.intercept_)
print('특성 갯수 : ', model.n_features_in_)

훈련 세트 정확도: , 0.6325
테스트 세트 정확도: , 0.61
분류 종류 :  [1 2 3]
가중치 값 :  [[-0.30481636  0.21455563 -0.12271819  1.09060047 -1.03116481]
 [ 0.34935398 -0.1135984  -0.0710581   0.11933871  0.00355792]
 [-0.04453762 -0.10095723  0.19377629 -1.20993917  1.02760689]]
절 편 값 :  [ 0.99877028  1.36461172 -2.363382  ]
특성 갯수 :  5


In [16]:
number = int(input("성적을 알고 싶은 학생의 번호를 입력하세요. : "))
print('로지스틱 예측: ', model.predict([data.loc[number].values]))
print('예측 값 확인: ',target.iloc[number])
print('------------------------------------------------------')
print('학생의 다른 정보: ','\n',data.iloc[number].values)

성적을 알고 싶은 학생의 번호를 입력하세요. : 1
로지스틱 예측:  [1]
예측 값 확인:  1
------------------------------------------------------
학생의 다른 정보:  
 [0 2 4 1 0]


In [17]:
## 교차 검증
from sklearn.model_selection import cross_val_score, cross_validate

# max_iter : 처음~끝까지 샘플데이터 학습 => 에포크(epoch) 학습 횟수 (기본 100)
lrModel=LogisticRegression(max_iter=500)

## 교차 검증으로 모델 학습 진행
## => 학습 데이터 기반 10개 Fold로 학습 & 검증 진행
result = cross_val_score(lrModel, data, target, cv=10)

In [18]:
# 10개 모델에 대한 정확도(accuracy)
result

array([0.61, 0.6 , 0.63, 0.64, 0.62, 0.65, 0.63, 0.65, 0.61, 0.6 ])

In [19]:
allResult=cross_validate(lrModel, data, target, 
                         return_train_score=True, 
                         cv=10)

In [20]:
resultDF=pd.DataFrame(allResult)
resultDF

fit_time  score_time  test_score  train_score
0  0.012963    0.001472        0.61     0.632222
1  0.010970    0.002035        0.60     0.632222
2  0.011006    0.000996        0.63     0.631111
3  0.012997    0.001000        0.64     0.627778
4  0.011964    0.001002        0.62     0.633333
5  0.012974    0.000985        0.65     0.627778
6  0.012970    0.001001        0.63     0.631111
7  0.013961    0.000996        0.65     0.631111
8  0.012968    0.000000        0.61     0.631111
9  0.010975    0.000990        0.60     0.631111

In [21]:
# 하이퍼 파라미터
from sklearn.model_selection import GridSearchCV

model=LogisticRegression()   # solver : {'newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'}
model.fit(train_X, train_y)

params = {"C": [0.001, 0.01, 0.1, 1, 10]}    #"penalty": ['l1','l2']}
grid_search = GridSearchCV(model, params, n_jobs=-1, cv=5, scoring='accuracy')
grid_search.fit(train_X, train_y)

print(grid_search.best_params_)
print('------------------------------')
print(grid_search.best_score_)
print('------------------------------')
print("최고 성능 모델: \n", grid_search.best_estimator_)

{'C': 0.1}
------------------------------
0.62625
------------------------------
최고 성능 모델: 
 LogisticRegression(C=0.1)


In [22]:
model2=LogisticRegression(C=0.1)  #penalty='l1', solver='liblinear'
model2.fit(train_X, train_y)

print('훈련 세트 정확도: ', model2.score(train_X, train_y))
print('------------------------------')
print('테스트 세트 정확도: ', model2.score(test_X, test_y))

훈련 세트 정확도:  0.63625
------------------------------
테스트 세트 정확도:  0.615


### 다른 모델
---

In [23]:
data1=stuDF[['gender','race/ethnicity','parental level of education','lunch','test preparation course']]
target1=stuDF['Rank']

In [24]:
print(data1.shape)
print(target1.shape)

(1000, 5)
(1000,)


In [25]:
# 훈련 테스트 분리
train_X, test_X, train_y, test_y = train_test_split(data1, target1,
                                                    test_size=0.2,
                                                   shuffle=True,
                                                    stratify=target,
                                                   random_state=42)

In [26]:
from sklearn.neighbors import RadiusNeighborsClassifier
neigh = RadiusNeighborsClassifier(radius=1.0)
neigh.fit(train_X, train_y)

RadiusNeighborsClassifier()

In [27]:
print(neigh.score(train_X, train_y))
print(neigh.score(test_X, test_y))

0.64625
0.615


In [28]:
# gender, race/ethnicity, parental level of education, lunch, test preparation course
# fe/ma, groupA~E, asso/bach/high/master/somecol/somehigh, free/reduce, com/non
RadiusNeighborsClassifier(...)
print(neigh.predict([[0, 1, 4, 1, 0]]))
print(neigh.predict([[1, 1, 4, 1, 0]]))
print('----------------------------------------------------------')
print(neigh.predict([[0, 1, 3, 1, 0]]))
print(neigh.predict([[1, 1, 3, 1, 0]]))
print('----------------------------------------------------------')
print(neigh.predict([[0, 3, 2, 1, 0]]))
print(neigh.predict([[1, 3, 2, 1, 0]]))

[1]
[1]
----------------------------------------------------------
[1]
[1]
----------------------------------------------------------
[1]
[1]


In [29]:
# gender, race/ethnicity, parental level of education, lunch, test preparation course
# fe/ma, groupA~E, asso/bach/high/master/somecol/somehigh, free/reduce, com/non
# 확률
print(neigh.predict_proba([[0, 1, 4, 1, 0]]))
print(neigh.predict_proba([[1, 1, 4, 1, 0]]))
print('----------------------------------------------------------')
print(neigh.predict_proba([[0, 1, 3, 1, 0]]))
print(neigh.predict_proba([[1, 1, 3, 1, 0]]))
print('----------------------------------------------------------')
print(neigh.predict_proba([[0, 3, 2, 1, 0]]))
print(neigh.predict_proba([[1, 3, 2, 1, 0]]))

[[0.59259259 0.37037037 0.03703704]]
[[0.57692308 0.42307692 0.        ]]
----------------------------------------------------------
[[0.75 0.25 0.  ]]
[[0.54545455 0.45454545 0.        ]]
----------------------------------------------------------
[[0.55555556 0.44444444 0.        ]]
[[0.48 0.48 0.04]]


In [30]:
##########################################################################

In [31]:
# from sklearn.naive_bayes import MultinomialNB

# rng= np.random.RandomState(50)

# num_data=50
# num_feature=10

# data2 = data1(5, size=(num_data, num_feature))
# target2 = target1.values(6, size=num_data)

In [32]:
# from numpy import mean
# from numpy import std
# from sklearn.datasets import make_classification
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import RepeatedStratifiedKFold
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.neighbors import RadiusNeighborsClassifier

# # define model
# neigh = RadiusNeighborsClassifier()

# # create pipeline
# pipeline = Pipeline(steps=[('norm', MinMaxScaler()),('neigh',neigh)])

# # define model evaluation method
# cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# # define grid
# grid = dict()
# grid['neigh_radius'] = arange(0.8, 1.5, 0.01)

# # define search
# search = GridSearchCV(pipeline, grid, scoring='accuracy', cv=cv, n_jobs=-1)

# # perform the search
# results = search.fit(train_X, train_y)

# # summarize
# print('Mean Accuracy: %.3f' % results.best_score_)
# print('Config: %s' % results.best_params_)