## Keras LIB
---
- Tensorflow 기반의 Keras 패키지
- 기본 데이터 Tensor 타입
- 모델을 직접 설계/생성 해야 함!!!

In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
from sklearn.datasets import load_iris

In [3]:
from keras import Sequential
from keras.layers import Dense

In [4]:
import tensorflow
tensorflow.__version__

'2.9.2'

In [5]:
## 데이터 로딩
iris=load_iris()

In [6]:
data=iris.data
target=iris.target

In [7]:
print(data.shape, target.shape)

(150, 4) (150,)


In [8]:
data[:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [9]:
target[:5], target[50:55], target[100:105]

(array([0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2]))

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [11]:
ohe=OneHotEncoder()
target_2=ohe.fit(target.reshape(-1, 1)).transform(target.reshape(-1,1))

In [12]:
type(target_2)

scipy.sparse.csr.csr_matrix

In [13]:
target_3=target_2.toarray()
type(target_3),     target_3[0], target_3[50], target_3[100], target_3.shape

(numpy.ndarray,
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 (150, 3))

In [14]:
model1=Sequential(name="iris")

In [15]:
# 첫번째 층은 반드시 입력정보 파라미터 설정 => input_shape=() 튜플, input_dim=숫자
# 각 노드(퍼셉트론, 유닛) : 4개 입력 / 출력 : 1개
# 총 10개가 다음 충(Layer)의 입력
l11=Dense(10, activation='relu', input_shape=(4,))

In [16]:
# 각 노드(퍼셉트론, 유닛) : 10개 입력 / 출력 : 1개
# 총 3개 출력
l22=Dense(3, activation='softmax')

In [17]:
model1.add(l11)
model1.add(l22)

In [18]:
model1.summary()

Model: "iris"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                50        
                                                                 
 dense_1 (Dense)             (None, 3)                 33        
                                                                 
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


In [19]:
model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### [1] 모델 구성
---

In [20]:
model=Sequential(name="HelloModel")

In [21]:
# 첫번째 층은 반드시 입력정보 파라미터 설정 => input_shape=() 튜플, input_dim=숫자
l1=Dense(10, activation='relu', input_shape=(5,))

In [22]:
# 각 노드(퍼셉트론, 유닛) : 10개 입력 / 출력 : 50
l2=Dense(50, activation='relu')

In [23]:
l3=Dense(5, activation='softmax')

In [24]:
model.add(l1)
model.add(l2)
model.add(l3)

In [25]:
## 모델 구성 확인 => summary()
model.summary()

Model: "HelloModel"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 10)                60        
                                                                 
 dense_3 (Dense)             (None, 50)                550       
                                                                 
 dense_4 (Dense)             (None, 5)                 255       
                                                                 
Total params: 865
Trainable params: 865
Non-trainable params: 0
_________________________________________________________________


### [2] 모델 생성
---
- 손실함수, 최적화 기법, 성능평가항목 설정
- compile() 메서드
    * optimizer : string 타입의 최적화기법명 입력 또는 객체 <- 기본값 사용하지 않는 경우
    * loss : 손실함수로 string 타입의 이름 입력
        - 분류 : categorical_crossentropy, sparse_categorical_crossentropy, binary_crossentropy
        - 회귀 : mean_squred_error, mean_absolute_error..
    * matrics : 모델 평가 항목
        - accuracy, mse, mae...

In [26]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

### [3] 학습
---
- fit() 메서드
    * 훈련용 데이터
    * 훈련용 타겟
    * epochs : 학습 횟수(처음~끝까지)
    * batch_size : 한번 학습량 (default:32)
    * validation_split / validation_data = (,) : 검증 데이터 설정
    * callbacks : 이벤트처리 함수 목록 (예: 학습중단 이벤트, 모델 검증 및 저장 이벤트...)
    * verbose : 학습 과정 출력 여부 설정 (기 : True)

In [27]:
model1.fit(data, target_3, epochs=5)

Epoch 1/5
5/5 [==============================] - 0s 2ms/step - loss: 1.0590 - accuracy: 0.3333
Epoch 2/5
5/5 [==============================] - 0s 1ms/step - loss: 1.0391 - accuracy: 0.3333
Epoch 3/5
5/5 [==============================] - 0s 2ms/step - loss: 1.0187 - accuracy: 0.3467
Epoch 4/5
5/5 [==============================] - 0s 997us/step - loss: 1.0005 - accuracy: 0.4267
Epoch 5/5
5/5 [==============================] - 0s 2ms/step - loss: 0.9833 - accuracy: 0.6467


### [4] 평가
---

In [28]:
## 평가
model1.evaluate([[5.1, 3.5, 1.4, 0.2]])

1/1 [==============================] - 0s 96ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


[0.0, 0.0]

In [29]:
model1.evaluate(data, target_3)

5/5 [==============================] - 0s 1ms/step - loss: 0.9741 - accuracy: 0.7467


[0.9741147756576538, 0.746666669845581]

### [5] 예측
---

In [30]:
model1.predict([[0, 1, 0, 1]])

1/1 [==============================] - 0s 85ms/step


array([[0.339514  , 0.35083136, 0.30965465]], dtype=float32)

In [31]:
## 예측
model1.predict([[5.1, 3.5, 1.4, 0.2]])

1/1 [==============================] - 0s 53ms/step


array([[0.44466576, 0.34999767, 0.2053366 ]], dtype=float32)