# Pytorch
---

## [1] Tensor 생성
---

In [1]:
import torch

In [2]:
torch.__version__

'1.12.1'

In [3]:
## [기본] tensor(data)
t1=torch.tensor([1,2,3], dtype=torch.int32)

In [4]:
type(t1), t1.shape, t1.dtype, t1.device

(torch.Tensor, torch.Size([3]), torch.int32, device(type='cpu'))

In [5]:
t2=torch.tensor([1.,2,3])

In [6]:
type(t2), t2.shape, t2.dtype, t2.device, t2.ndim

(torch.Tensor, torch.Size([3]), torch.float32, device(type='cpu'), 1)

In [7]:
t3=torch.tensor([[1.,2,3], [1,2,2]])

In [8]:
type(t3), t3.shape, t3.dtype, t3.device, t3.ndim

(torch.Tensor, torch.Size([2, 3]), torch.float32, device(type='cpu'), 2)

In [12]:
t4=torch.ones(size=(10,3))
t4

In [15]:
t4=torch.ones_like(t3)
t4

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
torch.zeros_like(t3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
t5=torch.zeros(size=(10,3))
t5

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.rand_like(t3)

tensor([[3.6877e-04, 8.9095e-01, 7.9487e-01],
        [5.8447e-01, 3.4968e-01, 1.4174e-01]])

In [19]:
t3.ndim, t3.shape

(2, torch.Size([2, 3]))

In [20]:
# 행 => [행인덱스]
t3[0]

tensor([1., 2., 3.])

In [21]:
t3[1]

tensor([1., 2., 2.])

In [23]:
# 열(column) => [행, 열]
t3[:, 0], t3[0,0]

(tensor([1., 1.]), tensor(1.))

In [24]:
t3.sum()

tensor(11.)

In [25]:
t3.mean()

tensor(1.8333)

In [26]:
t3.max()

tensor(3.)

In [27]:
torch.cuda.is_available()

False

In [29]:
## 파이토치로 구현한 퍼셉트론 (p.63)

import torch
import torch.nn as nn

class Perceptron(nn.Module):
    def __init__(self, input_dim):
        super(Perceptron, self).__init__()
        self.fc1 = nn.Linear(input_dim, 1)
        
    def forward(self, x_in):
        return torch.sigmoid(self.fc1(x_in)).squeeze()